# Generated by Django 4.2.1 on 2023-07-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desctiption',
            new_name='description',
        ),
    ]
